version: "3.7"
services:
  ordi1:
    image: weibeld/ubuntu-networking
    container_name: ubuntu1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    # networks:
   #   Reseau_prive:
    #    ipv4_address: 192.168.40.10
  
  routeur1:
    image: weibeld/ubuntu-networking
    container_name: box
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    networks:
#      - Reseau_prive:
        #ipv4_address: 192.168.40.20

      
       reseau_prive_bis:
        ipv4_address: 192.168.64.11
      #Réseau du swarm


  acces:
    build: ./image
    container_name: acces
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    privileged: true 
    networks:
    #  - reseaupublic:
       reseau_prive_bis:
        ipv4_address: 192.168.64.15
      #Réseau du swarm



networks: 
  #- Reseau_prive:
   # driver: overlay
    #attachable: true
    #driver_opts:
     # com.docker.network.bridge.name: br-1
   # ipam:
    #  config:
     #   - subnet: 192.168.40.0/24


  reseau_prive_bis:
    driver: overlay
    ipam:
      config:
        - subnet: 194.168.64.0/24
