version: "3.7"
services:
  
  acces_entreprise:
    build: ./image
    container_name: acces_entreprise
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    privileged: true 
    networks:
      reseaupublic:
        

networks: 
  reseaupublic:
#    driver: overlay
    attachable: true
#    driver_opts:
#      com.docker.network.bridge.name: br-1
    ipam:
      config:
        - subnet: 120.0.64.0/21
