version: "3.9"
services:
  ordi1:
    image: weibeld/ubuntu-networking
    container_name: ubuntu1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    networks:
      monReseau:
        ipv4_address: 6.6.6.10
  
  ordi2:
    image: weibeld/ubuntu-networking
    container_name: ubuntu2
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    networks:
      monReseau:
        ipv4_address: 6.6.6.6

networks: 
  monReseau:
    ipam:
      driver: default
      config:
        - subnet: 6.6.6.0/24
